package com.talentstream.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
@Entity
public class ApplicantSkills {
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;  // This ID will be generated by Hibernate

    private String skillName;
    double experience;

    // Define the ManyToMany relationship with ApplicantProfile
    @ManyToMany(fetch = FetchType.LAZY,
		      cascade = {
		              CascadeType.PERSIST,
		              CascadeType.MERGE
		          })
    @JsonIgnore
    private Set<ApplicantProfile> applicantProfiles = new HashSet<>();

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getSkillName() {
		return skillName;
	}

	public void setSkillName(String skillName) {
		this.skillName = skillName;
	}

	public Set<ApplicantProfile> getApplicantProfiles() {
		return applicantProfiles;
	}

	public void setApplicantProfiles(Set<ApplicantProfile> applicantProfiles) {
		this.applicantProfiles = applicantProfiles;
	}

	public double getExperience() {
		return experience;
	}

	public void setExperience(double experience) {
		this.experience = experience;
	}
    
    

}